/* 프로토타입: 인라인 데이터. 상용화 시 /data API(JSON)로 분리 예정 */

export const DATA = {
  quiz: [
    {
      id: 'q1',
      question: '오늘, 혀가 원하는 맛은?',
      options: [
        { label: '🍃 자극 없이 슴슴하게', tags: ['mild'] },
        { label: '🌶️ 콧등에 땀나게 맵게', tags: ['spicy'] },
        { label: '🧀 기름지고 진하게', tags: ['greasy'] },
      ],
    },
    {
      id: 'q2',
      question: '지금 당신의 멘탈 상태는?',
      options: [
        { label: '번아웃, 그냥 쉬고 싶다', tags: ['tired'] },
        { label: '오늘 누가 날 빡치게 함', tags: ['angry'] },
        { label: '꾸역꾸역 버티는 중', tags: ['survive'] },
      ],
    },
    {
      id: 'q3',
      question: '점심 예산, 솔직하게.',
      options: [
        { label: '카드값 무서운 거지', tags: ['broke'] },
        { label: '배달앱 쿠폰 있음', tags: ['normal'] },
        { label: '오늘은 좀 쓴다', tags: ['rich'] },
      ],
    },
  ],
  results: [
    // ── 기존 ──
    {
      id: 'pyeongnaengmyeon',
      tags: ['mild', 'tired', 'broke', 'normal'],
      emoji: '🍜',
      barcode: '5 9 5 9 · 0 0 0 1 · 1 2 3 0',
      menu: '평양냉면',
      message: '첫 입엔 무슨 맛인가 싶다가 결국 완냉하는 게 인생임. 자극 없는 게 제일 사치인 거, 오늘 알게 될 거임.',
      dosage: '면치기 금지, 천천히 음미',
      sideEffect: '"이게 맛있나?" 3분 후 중독',
      combo: '수육 한 점 (선택)',
      share: '결정장애로 30분 날리다 평양냉면 처방받음 🍜 슴슴한 게 어른의 맛이라며? #점심처방전 #평양냉면 #결정장애_치료완료',
    },
    {
      id: 'maeun-galbijjim',
      tags: ['spicy', 'angry', 'rich'],
      emoji: '🍖',
      barcode: '2 9 2 9 · 0 0 0 0 · 1 9 1 9',
      menu: '매운 갈비찜',
      message: '오늘 세상이 너한테 한 짓, 갈비 뜯으면서 다 갚아줄 거잖아. 단 내일 아침 화장실에서 2차 결전이 기다리고 있음.',
      dosage: '밥 두 공기 필수, 우유 대기',
      sideEffect: '내일 아침 2차 매운맛',
      combo: '아이스 음료 1.5L',
      share: '빡친 날엔 매운 갈비찜 처방 🌶️🔥 세상아 덤벼라 (입은 이미 항복함) #점심처방전 #매운갈비찜 #스트레스_혀로_해소',
    },
    {
      id: 'cheese-donkatsu',
      tags: ['greasy', 'survive', 'rich'],
      emoji: '🧀',
      barcode: '0 1 0 1 · 9 9 9 9 · 0 0 0 0',
      menu: '치즈 돈까스',
      message: '치즈 늘어나는 그 순간만큼은 버티는 게 보람 있음. 다이어트는 내일의 네가 알아서 함.',
      dosage: '치즈 늘어날 때 사진 필수',
      sideEffect: '오후 3시 식곤증 + 죄책감',
      combo: '제로콜라 (양심)',
      share: '버티는 중엔 치즈 돈까스 처방받음 🧀 다이어트는 내일의 내가 함 #점심처방전 #치즈돈까스 #느끼함이_답이다',
    },
    // ── 신규 ──
    {
      id: 'tteokbokki',
      tags: ['spicy', 'broke', 'normal'],
      emoji: '🌶️',
      barcode: '0 0 0 0 · 1 2 3 0 · 2 9 2 9',
      menu: '떡볶이',
      message: '통장은 바닥이고 속은 타들어가는 날, 그 감정 그대로 떡볶이집 가면 됨. 어묵 꼬치까지 얹으면 인생도 조금 나아지는 기분.',
      dosage: '국물 마지막 한 방울까지',
      sideEffect: '한 접시론 부족함 (치명적)',
      combo: '순대 or 튀김 1개',
      share: '지갑도 비고 속도 타는 날 떡볶이 처방받음 🌶️ 국물까지 마셔야 처방 완료 #점심처방전 #떡볶이 #통장이_문제가아니라_배가_문제',
    },
    {
      id: 'soondubu-jjigae',
      tags: ['mild', 'tired', 'rich'],
      emoji: '🥣',
      barcode: '1 2 3 0 · 5 9 5 9 · 0 0 0 0',
      menu: '순두부찌개',
      message: '번아웃엔 뜨끈한 뚝배기 앞에서 10분 멍 때리는 게 최고임. 두부처럼 스르르 넘어가다 보면 오늘 하루도 그냥 흘러감.',
      dosage: '뚝배기 식기 전에 섭취',
      sideEffect: '나른해서 오후 집중력 0',
      combo: '공깃밥 + 계란',
      share: '번아웃에 순두부찌개 처방받음 🥣 부드럽게 스르르 넘어가는 게 답이었음 #점심처방전 #순두부찌개 #번아웃엔_부드러운게_최고',
    },
    {
      id: 'jeyuk-bokkeum',
      tags: ['spicy', 'survive', 'normal'],
      emoji: '🥩',
      barcode: '2 5 2 5 · 1 2 3 0 · 0 0 0 1',
      menu: '제육볶음',
      message: '꾸역꾸역 버티는 몸에 고추장 제육 한 판 비벼 넣으면 오후 연료 충전됨. 밥이 자꾸 들어가는 게 이 메뉴의 유일한 단점.',
      dosage: '밥 비벼 먹기 (국룰)',
      sideEffect: '한 공기 추가 100% 확률',
      combo: '된장국 or 미소된장',
      share: '꾸역꾸역 버티는 날 제육볶음 처방받음 🥩 고추장 한 스푼이 오후 연료임 #점심처방전 #제육볶음 #생존식단',
    },
    {
      id: 'samgyeopsal',
      tags: ['greasy', 'angry', 'normal'],
      emoji: '🥓',
      barcode: '3 3 3 3 · 9 2 9 2 · 1 8 0 0',
      menu: '삼겹살',
      message: '불판 앞에서 쌈 싸다 보면 빡침이 어디 갔는지 모르게 됨. 직장 빡침은 회식 아닌 낮삼겹으로 푸는 거 아는 사람만 앎.',
      dosage: '불판 직화 굽기, 뒤집기 1회',
      sideEffect: '오후 내내 삼겹살 냄새',
      combo: '된장찌개 + 소주 (주의)',
      share: '빡친 날 삼겹살 처방받음 🥓 쌈장 올리면 세상이 용서됨 #점심처방전 #삼겹살 #낮삼겹은_치료제',
    },
    {
      id: 'salad',
      tags: ['mild', 'survive', 'rich'],
      emoji: '🥗',
      barcode: '1 0 0 4 · 0 0 0 0 · 0 1 0 1',
      menu: '샐러드',
      message: '오늘만큼은 진짜 어른인 척 해볼 수 있음. 드레싱은 반드시 따로 달라고 해라, 그게 샐러드 먹는 사람의 기본 자존심임.',
      dosage: '드레싱 뿌리지 말고 찍어 먹기',
      sideEffect: '2시간 후 또 배고픔 (치명적)',
      combo: '닭가슴살 or 계란 추가',
      share: '오늘만큼은 건강하게 샐러드 처방받음 🥗 드레싱은 따로 주세요 #점심처방전 #샐러드 #어른인척_프로젝트',
    },
    {
      id: 'budae-jjigae',
      tags: ['greasy', 'broke', 'normal'],
      emoji: '🍲',
      barcode: '0 6 2 5 · 1 9 4 5 · 2 0 2 5',
      menu: '부대찌개',
      message: '햄이랑 소시지랑 라면사리가 한 냄비에 다 들어가는 게 말이 됨? 냄비 바닥까지 긁어야 이 메뉴 제대로 먹은 거임.',
      dosage: '라면사리 추가는 필수',
      sideEffect: '나트륨 폭탄 (내일 얼굴)',
      combo: '공깃밥 + 김치',
      share: '지갑 얇은 날 부대찌개 처방받음 🍲 가성비 최강, 냄비 바닥까지 긁어야 진짜 #점심처방전 #부대찌개 #가성비_왕',
    },
    {
      id: 'bibimbap',
      tags: ['mild', 'angry', 'broke'],
      emoji: '🍚',
      barcode: '8 2 8 2 · 0 0 0 0 · 1 2 3 0',
      menu: '비빔밥',
      message: '빡쳤는데 슴슴한 게 당기는 거, 그게 진짜 지쳤다는 신호임. 고추장 넣고 빡침까지 있는 힘껏 비벼버려.',
      dosage: '밑에서부터 세게 비비기',
      sideEffect: '비빈 후 왜 화났는지 기억 안 남',
      combo: '달걀 프라이 (위에 올리기)',
      share: '빡치고 지갑도 비었을 때 비빔밥 처방받음 🥗 고추장이랑 빡침 같이 비볐더니 해결됨 #점심처방전 #비빔밥 #빡침은_비비면_해결',
    },
    {
      id: 'ramen',
      tags: ['greasy', 'tired', 'rich'],
      emoji: '🍥',
      barcode: '1 8 0 0 · 9 9 9 9 · 0 0 0 0',
      menu: '라멘',
      message: '차슈 올린 진국 한 숟가락이 링거보다 나음. 건강은 주말에 챙기고 오늘은 그냥 들이켜.',
      dosage: '면 먼저, 차슈는 마지막에',
      sideEffect: '나트륨 과다, 내일 붓기 보장',
      combo: '반숙란 추가 (필수)',
      share: '번아웃에 라멘 처방받음 🍜 차슈 올린 진국이 링거보다 나음 #점심처방전 #라멘 #피곤할땐_진국한그릇',
    },
    {
      id: 'malatang',
      tags: ['spicy', 'survive', 'rich'],
      emoji: '🫕',
      barcode: '1 2 1 2 · 0 0 0 0 · 9 9 9 9',
      menu: '마라탕',
      message: '먹고 싶은 거 다 집어넣는 게 마라탕의 본질임. 마라 향 한 번 훅 들어가면 버티던 몸에 정신이 번쩍 남.',
      dosage: '마라도 3~4단계 (겁쟁이 아니면)',
      sideEffect: '입술 얼얼 24시간 지속',
      combo: '탕후루 or 흑당 버블티',
      share: '버티다 지쳐서 마라탕 처방받음 🌶️✨ 먹고 싶은 거 다 넣으면 인생이 조금 나아짐 #점심처방전 #마라탕 #버티는중엔_마라가_답',
    },
    // ── fallback ──
    {
      fallback: true,
      id: 'kimchijjigae',
      tags: [],
      emoji: '🍜',
      barcode: '1 2 3 4 · 5 6 7 8 · 0 0 0 0',
      menu: '김치찌개',
      message: '메뉴 고민하다 점심시간 다 날린 거 실화임? 묻지도 따지지도 말고 김치찌개 가, 한국인 디폴트값엔 실패가 없음.',
      dosage: '공깃밥 추가는 국룰',
      sideEffect: '없음 (검증된 안전성)',
      combo: '계란말이 (있으면)',
      share: '뭐 먹을지 몰라서 김치찌개 처방받음 🍲 한국인 디폴트값은 실패가 없음 #점심처방전 #김치찌개 #무난한게_최고',
    },
  ],
};

export const LOADING_MESSAGES = [
  '처방전 조제 중...',
  '오늘의 당신을 진단하는 중...',
  '결정장애 치료제 선별 중...',
];
